### ISSUE TITLE
关于基和mark的来源？

### ISSUE THREAD

**Issue by lilililwj** [nzl5116190/Basisformer#11]
1.请问basis是如何得到的呢？
<img width="215" alt="微信图片_20241113165236" src="https://github.com/user-attachments/assets/a0f4a84f-08fd-428a-bbd2-05960ae02508">
这里的输入是什么？
2.这个mark指的是什么？它是如何得到的？
<img width="416" alt="微信图片_20241113165421" src="https://github.com/user-attachments/assets/7a2ab9fb-f446-4ca2-b1dc-dea96bb43b20">

**Comment by lilililwj** [comment]
![image](https://github.com/user-attachments/assets/197e089b-33ae-4d24-a48a-a6d982c5c78d)
这一步骤的feature和m1是coef模块中分别来自time series和basis的输入吗？

**Comment by nzl5116190** [comment]
English Reply:

Regarding question 1, as shown in the image below, we believe that the basis is a function of the timestamp. We take the normalized timestamp as input and pass it through a 4-layer Multi-Layer Perceptron (MLP) to obtain the basis functions.
<img width="724" alt="Screenshot 2024-11-16 at 00 23 46" src="https://github.com/user-attachments/assets/628680e8-2bd5-4092-b1ff-9b619ecd794c">

As for question 2, the "mark" refers to the timestamp, which is derived from the normalization process applied to the timestamps corresponding to each time point in the dataset. You can find the specific implementation in the data loader's code.

_________________________________________________________________________________________________________

中文回复(Chinese version)：

对于问题1，参考如下图片，我们认为basis是timestamp的一个函数。我们将归一化的timestamp作为输入，经过一个四层的多层感知机（MLP），从而得到基函数。
<img width="724" alt="Screenshot 2024-11-16 at 00 23 46" src="https://github.com/user-attachments/assets/628680e8-2bd5-4092-b1ff-9b619ecd794c">

对于问题2，mark指的是时间戳（timestamp），它是通过对数据集中每个时间点对应的时间戳进行归一化处理形成的，具体实现可以参考dataloader中的相关处理代码。

**Comment by lilililwj** [comment]
Thank you very much for your answer
