### ISSUE TITLE
Potential Redundancy in data_dict Entries

### ISSUE THREAD

**Issue by Gnaneshwari-S-19** [nzl5116190/Basisformer#4]
Upon reviewing the code, it appears that there are duplicate entries for Dataset_ETT_hour and Dataset_ETT_minute in the data_dict dictionary in the data_factory.py file. The entries are as follows:

    'ETTh1': Dataset_ETT_hour,
    'ETTh2': Dataset_ETT_hour,
    'ETTm1': Dataset_ETT_minute,
    'ETTm2': Dataset_ETT_minute,
    'custom': Dataset_Custom,

I would like to confirm whether this redundancy is intentional or if it might be an oversight. If it is intentional, could you please provide insights into the purpose of having two entries for each dataset? If it's unintentional, we might need to correct it for clarity.

Looking forward to clarification on this matter. Thank you!

**Comment by nzl5116190** [comment]
Hello!

Thank you for carefully reviewing the code and raising your concerns. To address your query, it's important to understand the structure of the ETT dataset. The ETT dataset comprises four subsets: ETTh1, ETTh2, ETTm1, and ETTm2. ETTh1 and ETTh2 represent hourly data, while ETTm1 and ETTm2 represent minute-level data.

In the data_dict dictionary you referred to, each key-value pair corresponds to a specific dataset class. ETTh1 and ETTh2 use the Dataset_ETT_hour class, and ETTm1 and ETTm2 use the Dataset_ETT_minute class. This design ensures that datasets of different granularities are processed correctly with their respective classes.

This is not a redundancy or duplication, but rather a method to ensure consistency and flexibility in data processing. It allows us to use specially tailored classes for different datasets, even if some classes have similar implementations across different datasets.

Finally, this design is based on the coding practices from previous work. Therefore, the purpose of this dictionary is merely to provide the correct class implementation for different datasets, without any issues of redundancy or duplication.

I hope this clarifies your question. Thank you for your interest and inquiry!

**Comment by Gnaneshwari-S-19** [comment]
Hello,

Thank you for the detailed clarification regarding the structure of the ETT dataset and the design choices made for handling different subsets. Your explanation makes sense, and I appreciate the effort to ensure consistency and flexibility in data processing. If there are any additional details or considerations that I should be aware of, or if you have further insights to share, I'd be interested to learn more.

Thanks again for your time and explanation!

**Comment by Gnaneshwari-S-19** [comment]
Hello, 
I'm encountering an issue while attempting to execute this code with my dataset. Specifically, when using values greater than 417, I'm facing a ValueError with the following traceback:

in data_provider(args, flag)
     38         freq=freq,
     39     )
---> 40     print(flag, len(data_set))
     41     data_loader = DataLoader(
     42         data_set,

ValueError: __len__() should return >= 0


I'm seeking assistance to understand the root cause of this error and whether there are any modifications required in the code to address it. Could you provide guidance on resolving this issue?"

**Comment by Gnaneshwari-S-19** [comment]
Hi there,

I hope this message finds you well. I've been using your code with my dataset, and I encountered an issue when working with values above 417. The error message I'm receiving is as follows:

in data_provider(args, flag)
    38         freq=freq,
    39     )
---> 40     print(flag, len(data_set))
    41     data_loader = DataLoader(
    42         data_set,

ValueError: __len__() should return >= 0


I'm reaching out to seek your guidance on understanding the root cause of this error. Do you have any insights into what might be causing it, and are there any specific changes you would recommend making to the code?

I appreciate your assistance and look forward to your guidance.

**Comment by Gnaneshwari-S-19** [comment]
Hello again,

I hope this message finds you well. I've been using your code with my dataset, and I encountered an issue when working with values above 417. The error message I'm receiving is as follows:

'''in data_provider(args, flag)
    38         freq=freq,
    39     )
---> 40     print(flag, len(data_set))
    41     data_loader = DataLoader(
    42         data_set,

ValueError: __len__() should return >= 0'''


I'm reaching out to seek your guidance on understanding the root cause of this error. Do you have any insights into what might be causing it, and are there any specific changes you would recommend making to the code?

I appreciate your assistance and look forward to your guidance.

**Comment by Gnaneshwari-S-19** [comment]
Hi there,

I hope this message finds you well. I've been using your code with my dataset, and I encountered an issue when working with values above 417. The error message I'm receiving is as follows:

'''
in data_provider(args, flag)
    38         freq=freq,
    39     )
---> 40     print(flag, len(data_set))
    41     data_loader = DataLoader(
    42         data_set,

ValueError: __len__() should return >= 0
'''

I'm reaching out to seek your guidance on understanding the root cause of this error. Do you have any insights into what might be causing it, and are there any specific changes you would recommend making to the code?

I appreciate your assistance and look forward to your guidance.

**Comment by Gnaneshwari-S-19** [comment]
```markdown
Error:
```
in data_provider(args, flag)
38 freq=freq,
39 )
---> 40 print(flag, len(data_set))
41 data_loader = DataLoader(
42 data_set,

ValueError: len() should return >= 0
```
```
