### ISSUE TITLE
In the implementation of BCAB, why does the ``series_out'' return to its input one? It seems that the cross-attention does not play a role in series representation.

### ISSUE THREAD

**Issue by zzwzz1998** [nzl5116190/Basisformer#5]
In the implementation of BCAB, why does the ``series_out'' return to its input one? It seems that the cross-attention does not play a role in series representation.

<img width="762" alt="image" src="https://github.com/nzl5116190/Basisformer/assets/43293548/fd64545d-4001-4e1d-99ec-c52642bd9239">

**Comment by nzl5116190** [comment]
Thank you for pointing this out. Indeed, the line returning `series_out` to its input was meant to be commented out. The latest version of the code has addressed this issue, and we appreciate your vigilance in catching this oversight. Thanks again for your contribution to improving the project!
