### ISSUE TITLE
About input data

### ISSUE THREAD

**Issue by Carrotsniper** [nzl5116190/Basisformer#7]
Thanks for your amazing work, my only question is what is the 
input called "mark"? 
![image](https://github.com/nzl5116190/Basisformer/assets/36280292/f5d9740e-3e0e-45b8-aa9b-111c7ccc7b5d)

**Comment by xxxxxx212121** [comment]
Are there external influences, such as temperature, humidity, etc.?

**Comment by nzl5116190** [comment]
Thank you for your interest in our work! In our context, "mark" refers to a timestamp. Specifically, it represents a sequence of timestamps that correspond one-to-one with the historical data “x”. Similarly, "y_mark" refers to a sequence of timestamps that correspond one-to-one with the future data “y”. This setup allows us to track and align the data points over time accurately.
