### ISSUE TITLE
about adabelief-pytorch version

### ISSUE THREAD

**Issue by lilililwj** [nzl5116190/Basisformer#9]
I was prompted with the following information during the training process：
Please check your arguments if you have upgraded adabelief-pytorch from version 0.0.5.
Modifications to default arguments:
                           eps  weight_decouple    rectify
-----------------------  -----  -----------------  ---------
adabelief-pytorch=0.0.5  1e-08  False              False
>=0.1.0 (Current 0.2.0)  1e-16  True               True
SGD better than Adam (e.g. CNN for Image Classification)    Adam better than SGD (e.g. Transformer, GAN)
----------------------------------------------------------  ----------------------------------------------
Recommended eps = 1e-8                                      Recommended eps = 1e-16
For a complete table of recommended hyperparameters, see
https://github.com/juntang-zhuang/Adabelief-Optimizer
You can disable the log message by setting "print_change_log = False", though it is recommended to keep as a reminder.

**Comment by nzl5116190** [comment]
Thank you for your question. The message you encountered is just a notification from the AdaBelief library and does not affect the training process.

In fact, we have specified the version of adabelief-pytorch as 0.2.1 in our requirements.txt. Additionally, in the main.py file, we have configured the optimizer as follows:

```
optimizer = AdaBelief(
    [{'params': para1, 'lr': 5e-3}, {'params': para2, 'lr': args.learning_rate}],
    eps=1e-16,
    betas=(0.9, 0.999),
    weight_decouple=True,
    rectify=False
)
```
This setup ensures that the mentioned parameters are already set correctly, so there should be no impact on functionality.

Please feel free to reach out if you have any further questions or concerns!
